theme: jekyll-theme-tactile
title: "NE 150 â€“ Discussion"
description: "Materials for the discussion section of UC Berkeley's Nuclear Engineering 150: Intro to Nuclear Reactor Theory."
markdown: kramdown
baseurl: /NE150-discussion
